### ISSUE TITLE
LS424 GPIO serial issue

### ISSUE THREAD

**Issue by elidonner** [zarpli/BSuControl#1]
Hi,

Thank you for sharing such a great resource! I am making a project for a museum exhibition.

I am using the LS424 with the 12 pin GPIO connector with pins 0 and 6 as rx and tx and wanted to make sure I understood the ReadMe correctly, is this connector not compatible with this autorun.brd file?

I am sure the serial signals I'm sending to the device are correct (verified with oscilloscope), but I get no response from the LS424.

Thank you in advance!

**Comment by zarpli** [comment]
hi,

the LS424 does not have native GPIO, is it using a USB-C to GPIO accessory?

**Comment by elidonner** [comment]
Thanks for the response. Yes, I am using the usb-c to GPIO accessory, the one that has 12 screw terminals. Not the one with 24 breakout pads.

**Comment by elidonner** [comment]
I have since ordered and been using the 24 pin breakout board, with no luck. I am using the arduino mega as shown in the YouTube video as well.

**Comment by elidonner** [comment]
Hi Zarpli,

I got the code to work and will close this issue. I needed to wait longer after power cycling the BrightSign for it to begin working. To work with a 3.3 volt microcontroller it also needs to be connected through a level shifter.

Thank you for the resource and have a wonderful day!
